### PR TITLE
styles.css

### PR DESCRIPTION
**Pull request by zeddkhan03**
I have changed the background colour. 🙃

### CODE REVIEW

**Comment by kanishak11-cyber** [comment]
add a screenshot and a short description what you have done in the changes

**Comment by zeddkhan03** [comment]
> add a screenshot and a short description what you have done in the changes
Screenshot 2022-10-30 at 3 31 15 PM

**Comment by zeddkhan03** [comment]
> add a screenshot and a short description what you have done in the changes
Screenshot 2022-10-30 at 3 31 34 PM

**Comment by zeddkhan03** [comment]
> add a screenshot and a short description what you have done in the changes

I have changed the background color from white to blue.

**Pull request merged**
